//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyclinicEntities1 : DbContext
    {
        private static PolyclinicEntities1 _context;
        public PolyclinicEntities1()
            : base("name=PolyclinicEntities1")
        {
        }
        public static PolyclinicEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new PolyclinicEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Otdels> Otdels { get; set; }
        public virtual DbSet<rols> rols { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vrach> Vrach { get; set; }
        public virtual DbSet<Record> Record { get; set; }
    }
}
