//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_pocient { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public Nullable<int> id_roll { get; set; }
    
        public virtual rols rols { get; set; }
    }
}
