//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrach
    {
        public int id_Vrach { get; set; }
        public Nullable<int> id_Otdels { get; set; }
        public string Fam { get; set; }
        public string Nam { get; set; }
        public string Ot { get; set; }
    
        public virtual Otdels Otdels { get; set; }
    }
}
